#!/SBUILD ver @v1.0.0
#SELF: https://raw.githubusercontent.com/pkgforge/soarpkgs/refs/heads/main/binaries/traefik/static.official.stable.yaml
_disabled: false

pkg: "traefik"
pkg_id: "github.com.traefik.traefik"
pkg_type: "static"
category:
  - "ConsoleOnly"
  - "Utility"
description: "High availability reverse proxy and load balancer"
distro_pkg:
  alpine:
    - "traefik"
  archlinux:
    aur:
      - "traefik-bin"
      - "traefik-git"
    extra:
      - "traefik"
  homebrew:
    - "traefik"
  nixpkgs:
    - "traefik"
homepage:
  - "https://github.com/traefik/traefik"
license:
  - id : "MIT"
    url: "https://github.com/traefik/traefik/raw/261e4395f3e28b4b7ed43ad1ba9b0bd63cca67e4/LICENSE.md"  
maintainer:
  - "Azathothas (https://github.com/Azathothas)"
note:
  - "[DO NOT RUN] (Meant for pkgforge CI Only)"
  - "Pre Built Binary Fetched from Upstream. Check/Report @ https://github.com/traefik/traefik"
provides:
  - "traefik"
repology:
  - "traefik"
src_url:
  - "https://github.com/traefik/traefik"
tag:
  - "load-balancer"
  - "proxy"
x_exec:
  host:
    - "aarch64-Linux"
    - "x86_64-Linux"
  shell: "bash"
  pkgver: |
    curl -qfsSL "https://api.gh.pkgforge.dev/repos/traefik/traefik/releases?per_page=100" | jq -r '[.[] | select(.draft == false)] | .[0].tag_name | gsub("\\s+"; "")' | tr -d '[:space:]'
  run: |
    #Download
    case "$(uname -m)" in
      aarch64)
        soar dl "https://github.com/traefik/traefik@${PKGVER}" --match "linux,arm64,tar" --exclude "amd64,x86,x64,sha256,sha512,bsd,macos,windows" -o "${SBUILD_TMPDIR}/${PKG}.archive" --yes
        ;;
      x86_64)
        soar dl "https://github.com/traefik/traefik@${PKGVER}" --match "linux,amd64,tar" --exclude "aarch,arm,i386,i686,sha256,sha512,bsd,macos,windows" -o "${SBUILD_TMPDIR}/${PKG}.archive" --yes
        ;;
    esac
    #Extract
    while E_X=$(find "${SBUILD_TMPDIR}" -type f -exec file -i "{}" + | 
     grep -E "archive|compressed|x-tar" |
     grep -iv "application/.*executable" |
     cut -d: -f1 | head -n1); [ -n "${E_X}" ]
     do
       7z e "${E_X}" -o"${SBUILD_TMPDIR}/." -y && {
        file -i "${E_X}" | grep -q "application/.*executable" && break
        rm -f "${E_X}"
       } || break
     done
    #Copy
    find "${SBUILD_TMPDIR}" -maxdepth 1 -type f -exec file -i "{}" \; | grep -Ei "application/.*executable|text/x-perl|text/.*script" | cut -d":" -f1 | xargs realpath | xargs -I "{}" rsync -achvL "{}" "${SBUILD_OUTDIR}/${PKG}"